syntax = "proto3";

package signaling;

// 声明生成 go 代码的 package 路径
option go_package = "github.com/Jingqi0327/GopherHole/proto/pb";

// 协调中心提供的控制面服务
service SignalingService {
  // 节点注册：上线时调用，获取分配的虚拟 IP
  rpc Register(RegisterRequest) returns (RegisterResponse) {}

  // 心跳与状态流：双向流，客户端定期上报自身状态，服务端下发在线节点列表及转发的信令
  rpc Heartbeat(stream HeartbeatRequest) returns (stream HeartbeatResponse) {}

  // 信令路由：客户端通过此接口向服务端发送打洞请求，服务端会通过目标客户端的 Heartbeat 流下发
  rpc SignalRoute(SignalMessage) returns (SignalMessageAck) {}
}

message RegisterRequest {
  // 可以包含主机名、OS信息或认证Token
  string requested_hostname = 1;
  // 期望的固定虚拟 IP（如 "10.8.0.5"），如果为空则由 Server 自动分配
  string requested_ip = 2;
}

message RegisterResponse {
  string hostname = 1;
  // Server 分配给 Client 的虚拟 IP (例如: "10.8.0.2")
  string virtual_ip = 2;
  // 客户端在公网侧的出口 IP（用于辅助 NAT 探测）
  string public_ip = 3;
}

message HeartbeatRequest {
  string hostname = 1;
  string virtual_ip = 2;
  // 客户端当前的 UDP 监听端口（预留给打洞阶段）
  int32 public_port = 3;
  // Client端的公钥,用于p2p隧道的加密
  bytes public_key = 4;
}

// 定义一个在线节点的信息
message RemotePeer {
  string hostname = 1;
  string virtual_ip = 2;
  string public_ip = 3;
  int32 public_port = 4;
  bytes public_key = 5;
}

message PeerList {
  repeated RemotePeer peers = 1;
}

// 采用 oneof 结构，使双向流既能下发节点列表，也能下发 P2P 信令
message HeartbeatResponse {
  oneof payload {
    PeerList peer_list = 1;
    SignalMessage signal = 2;
  }
}

// 通用的信令转发格式
message SignalMessage {
  string from_virtual_ip = 1;
  string to_virtual_ip = 2;

  enum Type {
    UNKNOWN = 0;
    REQUEST_PUNCH = 1; // 发起打洞请求
    PUNCH_ACK = 2;     // 目标端响应（可选）
  }
  Type type = 3; 
  // 可选的数据载荷，例如发送自己绑定的本地端口等
  bytes payload = 4;
}

message SignalMessageAck {
  bool success = 1;
  string err_msg = 2;
}
