// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: signaling.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalMessage_Type int32

const (
	SignalMessage_UNKNOWN       SignalMessage_Type = 0
	SignalMessage_REQUEST_PUNCH SignalMessage_Type = 1 // 发起打洞请求
	SignalMessage_PUNCH_ACK     SignalMessage_Type = 2 // 目标端响应（可选）
)

// Enum value maps for SignalMessage_Type.
var (
	SignalMessage_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "REQUEST_PUNCH",
		2: "PUNCH_ACK",
	}
	SignalMessage_Type_value = map[string]int32{
		"UNKNOWN":       0,
		"REQUEST_PUNCH": 1,
		"PUNCH_ACK":     2,
	}
)

func (x SignalMessage_Type) Enum() *SignalMessage_Type {
	p := new(SignalMessage_Type)
	*p = x
	return p
}

func (x SignalMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_signaling_proto_enumTypes[0].Descriptor()
}

func (SignalMessage_Type) Type() protoreflect.EnumType {
	return &file_signaling_proto_enumTypes[0]
}

func (x SignalMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalMessage_Type.Descriptor instead.
func (SignalMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{6, 0}
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 可以包含主机名、OS信息或认证Token
	RequestedHostname string `protobuf:"bytes,1,opt,name=requested_hostname,json=requestedHostname,proto3" json:"requested_hostname,omitempty"`
	// 期望的固定虚拟 IP（如 "10.8.0.5"），如果为空则由 Server 自动分配
	RequestedIp   string `protobuf:"bytes,2,opt,name=requested_ip,json=requestedIp,proto3" json:"requested_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_signaling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetRequestedHostname() string {
	if x != nil {
		return x.RequestedHostname
	}
	return ""
}

func (x *RegisterRequest) GetRequestedIp() string {
	if x != nil {
		return x.RequestedIp
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	VirtualIp     string                 `protobuf:"bytes,2,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	StunPorts     []int32                `protobuf:"varint,3,rep,packed,name=stun_ports,json=stunPorts,proto3" json:"stun_ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_signaling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterResponse) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *RegisterResponse) GetStunPorts() []int32 {
	if x != nil {
		return x.StunPorts
	}
	return nil
}

type HeartbeatRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Hostname  string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	VirtualIp string                 `protobuf:"bytes,2,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	// 客户端当前的 UDP 监听端口（预留给打洞阶段）
	PublicPort int32 `protobuf:"varint,3,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	// Client端的公钥,用于p2p隧道的加密
	PublicKey     []byte `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_signaling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HeartbeatRequest) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *HeartbeatRequest) GetPublicPort() int32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *HeartbeatRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// 定义一个在线节点的信息
type RemotePeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	VirtualIp     string                 `protobuf:"bytes,2,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	PublicIp      string                 `protobuf:"bytes,3,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	PublicPort    int32                  `protobuf:"varint,4,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemotePeer) Reset() {
	*x = RemotePeer{}
	mi := &file_signaling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemotePeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotePeer) ProtoMessage() {}

func (x *RemotePeer) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotePeer.ProtoReflect.Descriptor instead.
func (*RemotePeer) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{3}
}

func (x *RemotePeer) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RemotePeer) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *RemotePeer) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *RemotePeer) GetPublicPort() int32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *RemotePeer) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type PeerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*RemotePeer          `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerList) Reset() {
	*x = PeerList{}
	mi := &file_signaling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerList) ProtoMessage() {}

func (x *PeerList) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerList.ProtoReflect.Descriptor instead.
func (*PeerList) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{4}
}

func (x *PeerList) GetPeers() []*RemotePeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

// 采用 oneof 结构，使双向流既能下发节点列表，也能下发 P2P 信令
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HeartbeatResponse_PeerList
	//	*HeartbeatResponse_Signal
	Payload       isHeartbeatResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_signaling_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetPayload() isHeartbeatResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HeartbeatResponse) GetPeerList() *PeerList {
	if x != nil {
		if x, ok := x.Payload.(*HeartbeatResponse_PeerList); ok {
			return x.PeerList
		}
	}
	return nil
}

func (x *HeartbeatResponse) GetSignal() *SignalMessage {
	if x != nil {
		if x, ok := x.Payload.(*HeartbeatResponse_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

type isHeartbeatResponse_Payload interface {
	isHeartbeatResponse_Payload()
}

type HeartbeatResponse_PeerList struct {
	PeerList *PeerList `protobuf:"bytes,1,opt,name=peer_list,json=peerList,proto3,oneof"`
}

type HeartbeatResponse_Signal struct {
	Signal *SignalMessage `protobuf:"bytes,2,opt,name=signal,proto3,oneof"`
}

func (*HeartbeatResponse_PeerList) isHeartbeatResponse_Payload() {}

func (*HeartbeatResponse_Signal) isHeartbeatResponse_Payload() {}

// 通用的信令转发格式
type SignalMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromVirtualIp string                 `protobuf:"bytes,1,opt,name=from_virtual_ip,json=fromVirtualIp,proto3" json:"from_virtual_ip,omitempty"`
	ToVirtualIp   string                 `protobuf:"bytes,2,opt,name=to_virtual_ip,json=toVirtualIp,proto3" json:"to_virtual_ip,omitempty"`
	Type          SignalMessage_Type     `protobuf:"varint,3,opt,name=type,proto3,enum=signaling.SignalMessage_Type" json:"type,omitempty"`
	// 可选的数据载荷，例如发送自己绑定的本地端口等
	Payload       []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMessage) Reset() {
	*x = SignalMessage{}
	mi := &file_signaling_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMessage) ProtoMessage() {}

func (x *SignalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMessage.ProtoReflect.Descriptor instead.
func (*SignalMessage) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{6}
}

func (x *SignalMessage) GetFromVirtualIp() string {
	if x != nil {
		return x.FromVirtualIp
	}
	return ""
}

func (x *SignalMessage) GetToVirtualIp() string {
	if x != nil {
		return x.ToVirtualIp
	}
	return ""
}

func (x *SignalMessage) GetType() SignalMessage_Type {
	if x != nil {
		return x.Type
	}
	return SignalMessage_UNKNOWN
}

func (x *SignalMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SignalMessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMessageAck) Reset() {
	*x = SignalMessageAck{}
	mi := &file_signaling_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMessageAck) ProtoMessage() {}

func (x *SignalMessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMessageAck.ProtoReflect.Descriptor instead.
func (*SignalMessageAck) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{7}
}

func (x *SignalMessageAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignalMessageAck) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_signaling_proto protoreflect.FileDescriptor

const file_signaling_proto_rawDesc = "" +
	"\n" +
	"\x0fsignaling.proto\x12\tsignaling\"c\n" +
	"\x0fRegisterRequest\x12-\n" +
	"\x12requested_hostname\x18\x01 \x01(\tR\x11requestedHostname\x12!\n" +
	"\frequested_ip\x18\x02 \x01(\tR\vrequestedIp\"l\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x02 \x01(\tR\tvirtualIp\x12\x1d\n" +
	"\n" +
	"stun_ports\x18\x03 \x03(\x05R\tstunPorts\"\x8d\x01\n" +
	"\x10HeartbeatRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x02 \x01(\tR\tvirtualIp\x12\x1f\n" +
	"\vpublic_port\x18\x03 \x01(\x05R\n" +
	"publicPort\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\"\xa4\x01\n" +
	"\n" +
	"RemotePeer\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x02 \x01(\tR\tvirtualIp\x12\x1b\n" +
	"\tpublic_ip\x18\x03 \x01(\tR\bpublicIp\x12\x1f\n" +
	"\vpublic_port\x18\x04 \x01(\x05R\n" +
	"publicPort\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\fR\tpublicKey\"7\n" +
	"\bPeerList\x12+\n" +
	"\x05peers\x18\x01 \x03(\v2\x15.signaling.RemotePeerR\x05peers\"\x86\x01\n" +
	"\x11HeartbeatResponse\x122\n" +
	"\tpeer_list\x18\x01 \x01(\v2\x13.signaling.PeerListH\x00R\bpeerList\x122\n" +
	"\x06signal\x18\x02 \x01(\v2\x18.signaling.SignalMessageH\x00R\x06signalB\t\n" +
	"\apayload\"\xdf\x01\n" +
	"\rSignalMessage\x12&\n" +
	"\x0ffrom_virtual_ip\x18\x01 \x01(\tR\rfromVirtualIp\x12\"\n" +
	"\rto_virtual_ip\x18\x02 \x01(\tR\vtoVirtualIp\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.signaling.SignalMessage.TypeR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"5\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x11\n" +
	"\rREQUEST_PUNCH\x10\x01\x12\r\n" +
	"\tPUNCH_ACK\x10\x02\"E\n" +
	"\x10SignalMessageAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg2\xef\x01\n" +
	"\x10SignalingService\x12E\n" +
	"\bRegister\x12\x1a.signaling.RegisterRequest\x1a\x1b.signaling.RegisterResponse\"\x00\x12L\n" +
	"\tHeartbeat\x12\x1b.signaling.HeartbeatRequest\x1a\x1c.signaling.HeartbeatResponse\"\x00(\x010\x01\x12F\n" +
	"\vSignalRoute\x12\x18.signaling.SignalMessage\x1a\x1b.signaling.SignalMessageAck\"\x00B+Z)github.com/Jingqi0327/GopherHole/proto/pbb\x06proto3"

var (
	file_signaling_proto_rawDescOnce sync.Once
	file_signaling_proto_rawDescData []byte
)

func file_signaling_proto_rawDescGZIP() []byte {
	file_signaling_proto_rawDescOnce.Do(func() {
		file_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signaling_proto_rawDesc), len(file_signaling_proto_rawDesc)))
	})
	return file_signaling_proto_rawDescData
}

var file_signaling_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_signaling_proto_goTypes = []any{
	(SignalMessage_Type)(0),   // 0: signaling.SignalMessage.Type
	(*RegisterRequest)(nil),   // 1: signaling.RegisterRequest
	(*RegisterResponse)(nil),  // 2: signaling.RegisterResponse
	(*HeartbeatRequest)(nil),  // 3: signaling.HeartbeatRequest
	(*RemotePeer)(nil),        // 4: signaling.RemotePeer
	(*PeerList)(nil),          // 5: signaling.PeerList
	(*HeartbeatResponse)(nil), // 6: signaling.HeartbeatResponse
	(*SignalMessage)(nil),     // 7: signaling.SignalMessage
	(*SignalMessageAck)(nil),  // 8: signaling.SignalMessageAck
}
var file_signaling_proto_depIdxs = []int32{
	4, // 0: signaling.PeerList.peers:type_name -> signaling.RemotePeer
	5, // 1: signaling.HeartbeatResponse.peer_list:type_name -> signaling.PeerList
	7, // 2: signaling.HeartbeatResponse.signal:type_name -> signaling.SignalMessage
	0, // 3: signaling.SignalMessage.type:type_name -> signaling.SignalMessage.Type
	1, // 4: signaling.SignalingService.Register:input_type -> signaling.RegisterRequest
	3, // 5: signaling.SignalingService.Heartbeat:input_type -> signaling.HeartbeatRequest
	7, // 6: signaling.SignalingService.SignalRoute:input_type -> signaling.SignalMessage
	2, // 7: signaling.SignalingService.Register:output_type -> signaling.RegisterResponse
	6, // 8: signaling.SignalingService.Heartbeat:output_type -> signaling.HeartbeatResponse
	8, // 9: signaling.SignalingService.SignalRoute:output_type -> signaling.SignalMessageAck
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_signaling_proto_init() }
func file_signaling_proto_init() {
	if File_signaling_proto != nil {
		return
	}
	file_signaling_proto_msgTypes[5].OneofWrappers = []any{
		(*HeartbeatResponse_PeerList)(nil),
		(*HeartbeatResponse_Signal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signaling_proto_rawDesc), len(file_signaling_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signaling_proto_goTypes,
		DependencyIndexes: file_signaling_proto_depIdxs,
		EnumInfos:         file_signaling_proto_enumTypes,
		MessageInfos:      file_signaling_proto_msgTypes,
	}.Build()
	File_signaling_proto = out.File
	file_signaling_proto_goTypes = nil
	file_signaling_proto_depIdxs = nil
}
