// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: signaling.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 可以包含主机名、OS信息或认证Token
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// 期望的固定虚拟 IP（如 "10.8.0.5"），如果为空则由 Server 自动分配
	RequestedIp   string `protobuf:"bytes,2,opt,name=requested_ip,json=requestedIp,proto3" json:"requested_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_signaling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetRequestedIp() string {
	if x != nil {
		return x.RequestedIp
	}
	return ""
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server 分配给 Client 的虚拟 IP (例如: "10.8.0.2")
	VirtualIp string `protobuf:"bytes,1,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	// 客户端在公网侧的出口 IP（用于辅助 NAT 探测）
	PublicIp      string `protobuf:"bytes,2,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_signaling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *RegisterResponse) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

type HeartbeatRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	VirtualIp string                 `protobuf:"bytes,1,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	// 客户端当前的 UDP 监听端口（预留给打洞阶段）
	PublicPort    int32 `protobuf:"varint,2,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_signaling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *HeartbeatRequest) GetPublicPort() int32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

// 定义一个在线节点的信息
type RemotePeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VirtualIp     string                 `protobuf:"bytes,1,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	PublicIp      string                 `protobuf:"bytes,2,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	PublicPort    int32                  `protobuf:"varint,3,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemotePeer) Reset() {
	*x = RemotePeer{}
	mi := &file_signaling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemotePeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotePeer) ProtoMessage() {}

func (x *RemotePeer) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotePeer.ProtoReflect.Descriptor instead.
func (*RemotePeer) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{3}
}

func (x *RemotePeer) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *RemotePeer) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *RemotePeer) GetPublicPort() int32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 下发当前所有在线节点的信息
	Peers         []*RemotePeer `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_signaling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetPeers() []*RemotePeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

// 通用的信令转发格式
type SignalMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromVip       string                 `protobuf:"bytes,1,opt,name=from_vip,json=fromVip,proto3" json:"from_vip,omitempty"`
	ToVip         string                 `protobuf:"bytes,2,opt,name=to_vip,json=toVip,proto3" json:"to_vip,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`       // 信令类型：RequestPunch, PunchAck 等
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // 具体数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMessage) Reset() {
	*x = SignalMessage{}
	mi := &file_signaling_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMessage) ProtoMessage() {}

func (x *SignalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMessage.ProtoReflect.Descriptor instead.
func (*SignalMessage) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{5}
}

func (x *SignalMessage) GetFromVip() string {
	if x != nil {
		return x.FromVip
	}
	return ""
}

func (x *SignalMessage) GetToVip() string {
	if x != nil {
		return x.ToVip
	}
	return ""
}

func (x *SignalMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SignalMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_signaling_proto protoreflect.FileDescriptor

const file_signaling_proto_rawDesc = "" +
	"\n" +
	"\x0fsignaling.proto\x12\tsignaling\"P\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12!\n" +
	"\frequested_ip\x18\x02 \x01(\tR\vrequestedIp\"N\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x01 \x01(\tR\tvirtualIp\x12\x1b\n" +
	"\tpublic_ip\x18\x02 \x01(\tR\bpublicIp\"R\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x01 \x01(\tR\tvirtualIp\x12\x1f\n" +
	"\vpublic_port\x18\x02 \x01(\x05R\n" +
	"publicPort\"i\n" +
	"\n" +
	"RemotePeer\x12\x1d\n" +
	"\n" +
	"virtual_ip\x18\x01 \x01(\tR\tvirtualIp\x12\x1b\n" +
	"\tpublic_ip\x18\x02 \x01(\tR\bpublicIp\x12\x1f\n" +
	"\vpublic_port\x18\x03 \x01(\x05R\n" +
	"publicPort\"@\n" +
	"\x11HeartbeatResponse\x12+\n" +
	"\x05peers\x18\x01 \x03(\v2\x15.signaling.RemotePeerR\x05peers\"o\n" +
	"\rSignalMessage\x12\x19\n" +
	"\bfrom_vip\x18\x01 \x01(\tR\afromVip\x12\x15\n" +
	"\x06to_vip\x18\x02 \x01(\tR\x05toVip\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload2\xec\x01\n" +
	"\x10SignalingService\x12E\n" +
	"\bRegister\x12\x1a.signaling.RegisterRequest\x1a\x1b.signaling.RegisterResponse\"\x00\x12L\n" +
	"\tHeartbeat\x12\x1b.signaling.HeartbeatRequest\x1a\x1c.signaling.HeartbeatResponse\"\x00(\x010\x01\x12C\n" +
	"\vSignalRoute\x12\x18.signaling.SignalMessage\x1a\x18.signaling.SignalMessage\"\x00B+Z)github.com/Jingqi0327/GopherHole/proto/pbb\x06proto3"

var (
	file_signaling_proto_rawDescOnce sync.Once
	file_signaling_proto_rawDescData []byte
)

func file_signaling_proto_rawDescGZIP() []byte {
	file_signaling_proto_rawDescOnce.Do(func() {
		file_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signaling_proto_rawDesc), len(file_signaling_proto_rawDesc)))
	})
	return file_signaling_proto_rawDescData
}

var file_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_signaling_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: signaling.RegisterRequest
	(*RegisterResponse)(nil),  // 1: signaling.RegisterResponse
	(*HeartbeatRequest)(nil),  // 2: signaling.HeartbeatRequest
	(*RemotePeer)(nil),        // 3: signaling.RemotePeer
	(*HeartbeatResponse)(nil), // 4: signaling.HeartbeatResponse
	(*SignalMessage)(nil),     // 5: signaling.SignalMessage
}
var file_signaling_proto_depIdxs = []int32{
	3, // 0: signaling.HeartbeatResponse.peers:type_name -> signaling.RemotePeer
	0, // 1: signaling.SignalingService.Register:input_type -> signaling.RegisterRequest
	2, // 2: signaling.SignalingService.Heartbeat:input_type -> signaling.HeartbeatRequest
	5, // 3: signaling.SignalingService.SignalRoute:input_type -> signaling.SignalMessage
	1, // 4: signaling.SignalingService.Register:output_type -> signaling.RegisterResponse
	4, // 5: signaling.SignalingService.Heartbeat:output_type -> signaling.HeartbeatResponse
	5, // 6: signaling.SignalingService.SignalRoute:output_type -> signaling.SignalMessage
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_signaling_proto_init() }
func file_signaling_proto_init() {
	if File_signaling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signaling_proto_rawDesc), len(file_signaling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signaling_proto_goTypes,
		DependencyIndexes: file_signaling_proto_depIdxs,
		MessageInfos:      file_signaling_proto_msgTypes,
	}.Build()
	File_signaling_proto = out.File
	file_signaling_proto_goTypes = nil
	file_signaling_proto_depIdxs = nil
}
